# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb0f47ff5a670ce687f1d24a30ea207ef302490e90152b5fe81c7bfccdd191f64d4183f270c1d48135b7a101d66609da2315b458b925e57860f0c63521a22bb1

test:
  secret_key_base: ad5351c5f845c1a3522f6cc1b8b0a74254179db1ef9920998d941449956af860d303885c5b225454931f62f0f0bd02f29b3561f1743376d4c48587c3546a5d83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
